# Generated by Django 5.1 on 2024-09-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('presenters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='presenters.presenter'),
            preserve_default=False,
        ),
    ]
